### ISSUE TITLE
Unable to build Python SDK for Multi Language Component  when using Python 3.12.X

### ISSUE THREAD

**Issue by aureq** [pulumi/pulumi-component-provider-ts-boilerplate#56]
### What happened?

When using GitHub Actions, it's possible to build the Python SDK of a Multi Language Component when Python 3.11.X is used ✅. However, if Python is bumped to 3.12.X (either 3.12.0 or 3.12.1) the build fails unexpectedly❌with the error message shown below.

![image](https://github.com/pulumi/pulumi-component-provider-ts-boilerplate/assets/1161681/3b4363fb-332e-4c3d-a367-24a7ee0f1c96)

The only change in the GitHub action is shown below.
![image](https://github.com/pulumi/pulumi-component-provider-ts-boilerplate/assets/1161681/178408db-68fc-448c-b086-b96f59c1e58f)

### Example

n/a

### Output of `pulumi about`

n/a

### Additional context

Could this be somehow related to previous work done to support Python 3.12? https://github.com/pulumi/pulumi/issues/14258

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by mjeffryes** [comment]
Based on some local debugging, I think this fails with python 3.12 simply because `setuptools` is no longer bundled with the python install ([What’s New In Python 3.12](https://docs.python.org/dev/whatsnew/3.12.html#ensurepip)). It can be fixed simply by adding a `pip install setuptools` step after the `setup-python` action runs ([ie. line 98 in sample release job](https://github.com/pulumi/pulumi-component-provider-ts-boilerplate/blob/802b7db5ec37c5e22a6733cc87e184be6a8c74aa/deployment-templates/release.yml#L98).
